---
linters-settings:
  # prevent import of "errors" instead of "github.com/pkg/errors"
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors

  goimports:
    local-prefixes: github.com/percona/qan-api2

  lll:
    line-length: 140
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    algo: rta
    check-exported: true

linters:
  enable-all: true

# options for analysis running
run:
  skip-dirs:
    - migrations

issues:
  exclude-use-default: false

  exclude-rules:
    - path: ./
      text: 'U1000: .* is unused'
    - path: ./
      text: '.* is a global variable'
    - path: _test\.go
      text: '.* lines are duplicate of .*'
    - path: _test\.go
      text: 'Using the variable on range scope .* in function literal'

  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
