[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.5.4"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kshvakov/clickhouse"
  version = "1.3.5"

[[constraint]]
  branch = "master"
  name = "github.com/percona/go-mysql"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"
