# tools
required = [
  "github.com/kevinburke/go-bindata/go-bindata"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  #branch = "PMM-2.0"
  branch = "PMM-3630-metrics-dimensions-list"

[[constraint]]
  branch = "PMM-3514-group-by-digest-user-host-db-server"
  name = "github.com/percona/go-mysql"
