name: Go

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.15
        include:
          - go-version: 1.16
            os: ubuntu-latest
            may-fail: true
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: percona-platform/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: percona-platform/checkout@v2
    - name: Prepare
      run: |
        make init gen format
        git status
        git diff --exit-code
    - name: Run checks
      run: |
        bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number | env REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
        bin/golangci-lint run -c=.golangci.yml --out-format=line-number | env REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-review
        go run .github/check-license.go
    - name: Run Tests
      run: |
        make install
        make test-env-up
        make test-race
        make test-cover
    - name: Run debug commands on failure
      if: ${{ failure() }}
      run: |
        env
        go version
        go env
        pwd
        git status
